### ISSUE TITLE
[BUG] I cant move

### ISSUE THREAD

**Issue by Medatur76** [WeatherElectric/ContentWarning#1]
**State Which Mod**
_ContentPresence_
**Describe the bug**
When I run the game (without the mod but with its dependencies) the game runs fine, not problems at all, but when I run the game with ContentPresence installed and start to host a match my mouse is still present on my screen and I cant move, I can still get to the menu fine but my character is non responsive
**To Reproduce**
1. Install the mod and its dependencies
2. Run the game
3. Host a game

**Expected behavior**
You will load into your save just fine but your mouse will still be on screen and your cant move your character
**Screenshots**
[Photo](https://steamcommunity.com/id/Medaturd76/screenshot/2456230880770656045/)
**Additional context**
I think this is related but when I run the mod I get this error after starting the game and it just keeps going:
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CursorHandler.Update () (at <4ba1b5dae58b4b50adb32699bbdb4490>:0)`

**Comment by SoulWithMae** [comment]
Mod's kinda useless now that the game has its own discord rich presence

**Comment by Medatur76** [comment]
k, close it?
